---
# add the users 

- name: adduser {{ user_name }}
  user: 
    name: "{{ user_name }}"

- name: authkey for {{ user_name }}
  authorized_key: 
    user: "{{ user_name }}"
    key: "{{bootstrap_key_url}}/{{user_name}}.key"
    state: present
