---
# add users plus security

- name: loop through users
  include_tasks: add-users.yml
  loop: "{{bootstrap_users}}"
  loop_control:
    loop_var: user_name
   
- name: disable root ssh
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart_ssh
